[build]
  command = "npm run build:fns" # the command you run to build this file
  functions = "dist/functions"
  publish = "dist/browser" # CLI builds to this folder, Netlify should serve all these files statically

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
