[build]
  command = "npm run build:ssr" # the command you run to build this file
  functions = "lambda"
  publish = "dist/browser" # create-react-app builds to this folder, Netlify should serve all these files statically
